<template>
  <div class="content">
    <div class="content-wrap">
      <div class="work">
        <!-- Mobile Header -->
        <div class="work-mobile-header">
          <div class="work-data">
            <div class="work-block owner">
              <OwnerProfile
                owner="木内达朗"
                className="owner-info-header"
              />
            </div >
            <div class="highlight">
              <div id="" class="work-block">
                <div class="work-title">白狐</div>
                <div class="work-fields">
                  <ul id="work-fields-list">
                    <li class="work-fields-item"><a href="">艺术指导</a>, </li>
                    <li class="work-fields-item"><a href="">动态图像</a></li>
                  </ul>
                </div>
                <div class="work-time">
                  发布时间: <span>2018年12月17日</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Work Content -->
        <div class="work-content">
          <div class="work-content-wrap work-content-style">
            <div class="work-modules">
              <!-- This module can be generated by rich editor -->
              <!-- place holder 1400 x 1 px -->
              <div class="module-spacer">
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABXgAAAABCAYAAABkHsaZAAAAHElEQVR42u3BAQ0AAADCoPdPbQ43oAAAAAAAuDQV4QABsr+jcAAAAABJRU5ErkJggg==" />
              </div>
              <div class="work-module module module-image image-full">
                <div class="module-image-wrap">
                  <img
                    class="js-project-module--picture"
                    src="https://c.pxhere.com/images/55/fe/90b7264e402241035856cd169d76-1418846.jpg!d"
                  >
                </div>
              </div>
              <div class="spacer">
                <div class="divider" />
              </div>
              <div class="work-module module module-text align-center">
                <div class="main-text">
                  <div>A book cover and interior illustrations for The White Fox (Japanese edition),&nbsp;a novel by Jackie Morris.</div><div>Publisher: Asunaro Shobo</div><div><br>あすなろ書房より刊行のジャッキー・モリス&nbsp;(著)、千葉 茂樹&nbsp;(翻訳)『ソロモンの白いキツネ』のためのイラストレーション。デザインは城所潤さん（<a href="http://www.jkd.co.jp/" target="_blank">JUN KIDOKORO DESIGN</a>）です。<a href="https://www.amazon.co.jp/%25E3%2582%25BD%25E3%2583%25AD%25E3%2583%25A2%25E3%2583%25B3%25E3%2581%25AE%25E7%2599%25BD%25E3%2581%2584%25E3%2582%25AD%25E3%2583%2584%25E3%2583%258D-%25E3%2582%25B8%25E3%2583%25A3%25E3%2583%2583%25E3%2582%25AD%25E3%2583%25BC%25E3%2583%25BB%25E3%2583%25A2%25E3%2583%25AA%25E3%2582%25B9/dp/4751529331/ref=as_li_ss_tl?ie=UTF8&amp;qid=1544353335&amp;sr=8-1&amp;keywords=%25E3%2582%25BD%25E3%2583%25AD%25E3%2583%25A2%25E3%2583%25B3%25E3%2581%25AE%25E7%2599%25BD%25E3%2581%2584%25E3%2582%25AD%25E3%2583%2584%25E3%2583%258D&amp;linkCode=ll1&amp;tag=tatsurokiuc01-22&amp;linkId=388f091ee3c451be97ab449ef08b8691&amp;language=ja_JP" target="_blank">ご購入はこちら→Amazon.co.jp</a></div>
                </div>
              </div>
              <div class="spacer">
                <div class="divider" />
              </div>
              <div class="work-module module module-image">
                <div class="module-image-wrap">
                  <img
                    class="js-project-module--picture"
                    src="https://c.pxhere.com/images/a0/8f/48570a016d6781b48a49896e6524-1446645.jpg!d"
                  >
                </div>
              </div>
            </div>
            <div class="spacer">
              <div class="divider"></div>
            </div>
          </div>
        </div>
        <!-- Work Sharing -->
        <div class="work-sharing">
          <div class="sharing-links">
            <a class="sharing-link">
              <span>Add to Collection</span>
            </a>
            <a class="sharing-link">
              <span>Copy link</span>
            </a>
          </div>
        </div>
        <!-- Owner Profile -->
        <div class="work-owner-profile zfix">
          <div class="work-owner-profile-wrap">
            <div class="work-owner-profile-info">
              <OwnerProfile
                owner="木内达朗"
                className="owner-info-bar"
              />
            </div>
          </div>
        </div>
        <!-- Other Works -->
        <OtherWorks />
        <!-- Work Footer -->
        <Comments />
      </div>
    </div>
  </div>
</template>

<script>
import OwnerProfile from '@/components/profile/owner';
import OtherWorks from '@/components/work/others';
import Comments from '@/components/comment';

export default {
  components: {
    OwnerProfile,
    OtherWorks,
    Comments,
  },
};
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
  .zfix {
    zoom: 1;
  }
  .content {
    position: relative;
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    padding: 50px 50px 96px;
    text-align: center;
    z-index: 1;
  }

  .content, .content * {
    box-sizing: border-box;
  }

  .content-wrap {
    position: relative;
    display: inline-block;
    max-width: 100%;
    margin-bottom: 150px;
    background: #fafafa;
    border-radius: 3px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.2);
    text-align: left;
    .work {
      position: relative;
      z-index: 1;
    }
  }

  .work {
    max-width: 1400px;
    min-width: 700px;
    margin-right: 280px;
  }

  .work-mobile-header {
    border-bottom: 1px solid #e8e8e8;
    display: none;
    width: 100%;
    .work-data {
      border-bottom: 1px solid #e8e8e8;
      display: inline-block;
      height: 111px;
      padding: 20px;
      width: 100%;
    }
    .work-block {
      border-bottom-width: 0;
      padding: 0;
    }
    .highlight {
      display: inline-block;
      position: relative;
    }
  }

  .work-block {
    position: relative;
    clear: left;
    float: left;
    color: #6f6f6f;
    font-size: 13px;
    line-height: 19px;
    padding: 20px;
    width: 100%;
    word-wrap: break-word;
    border-bottom: 1px solid #e8e8e8;
    z-index: 3;
  }

  .work-title {
    color: #262626;
    display: inline-block;
    font-size: 16px;
    font-weight: bold;
    max-width: 100%;
    word-wrap: break-word;
  }

  .work-fields {
    font-size: 13px;
    line-height: 18px;
    margin: 2px 0 0;
  }

  .work-fields-item {
    display: inline;
    a {
      color: dimgray;
    }
  }

  .work-time {
    color: #a4a4a4;
    font-size: 11px;
    margin: 10px 0 0;
  }

  .work-content {
    padding-top: 0;
    background-color: #FFFFFF;
    border-radius: 3px 0 0;
  }

  .work-content-wrap {
    .work-modules {
      border-radius: 0;
      overflow: hidden;
    }
  }

  .work-content-style {
    .main-text {
      color: #696969;
      font-family: arial,helvetica,sans-serif;
      font-size: 20px;
      font-style: normal;
      font-weight: normal;
      line-height: 1.4em;
      text-align: left;
      text-decoration: none;
    }
  }

  .module {
    padding-bottom: 0px;
  }

  .work-module {
    padding: 0 7.1%;
    .main-text a {
      color: #1769FF;
      text-align: left;
      text-decoration: none;
    }
    &.module-text {
      margin: 0 auto;
      max-width: calc(800px + 14.2%);
      word-wrap: break-word;
      &.align-center {
        margin-center: 0 !important;
      }
    }
    &.image-full {
      padding-left: 0;
      padding-right: 0;
    }
  }

  .module-image-wrap {
    display: inline-block;
    max-width: 100%;
  }

  .module-image {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
    img {
      height: 100%;
      width: 100%;
      display: inline-block;
      max-width: 100%;
      vertical-align: middle;
    }
  }

  .module-spacer {
    height: 0;
    img {
      width: 100%;
    }
  }

  .spacer, .module-separator {
    height: 60px;
  }

  .divider {
    display: none;
  }

  .work-sharing {
    -ms-flex-align: center;
    align-items: center;
    background: #212121;
    display: -ms-flexbox;
    display: flex;
    height: 44px;
    -ms-flex-pack: justify;
    justify-content: space-between;
    padding: 0 26px;
    .sharing-link {
      color: #b8b8b8;
      font-size: 10px;
      text-decoration: none;
      text-transform: uppercase;
    }
    .sharing-link:first-child {
      margin-right: 15px;
    }
  }

  .work-owner-profile {
    background: #161616;
    padding: 25px;
  }

  .work-owner-profile-wrap {
    margin: auto;
    max-width: 1205px;
    position: relative;
  }

  .work-owner-profile-info {
    max-width: calc(100% - 185px);
  }

  .owner-info-bar {
    height: 90px;
  }

  .work-owner-profile-list {
    padding-top: 0;
    margin-bottom: 15px;
    overflow: hidden;
    position: relative;
  }


  .work-others {

  }

  .work-footer {

  }

  @media (max-width: 603px) {
    .content {
      padding-top: 29px;
    }
    .work-owner-profile {
      padding: 15px;
    }
    .work-owner-profile-info {
      max-width: 100%;
    }
    .work-mobile-header {
      .work-data {
        height: auto;
        padding: 0;
        border-bottom-width: 0;
      }
      .work-block {
        padding: 0;
        border-bottom-width: 0;
      }
      .owner {
        padding: 8px 14px;
      }
      .highlight {
        border-top: 1px solid #e8e8e8;
        padding: 8px 14px 7px;
        width: 100%;
      }
    }
  }


  @media (min-width: 604px) and (max-width: 1024px) {
    .work-mobile-header {
      border-bottom: none;
      .owner {
        float: right;
        padding: 7px 0 0 20px;
        width: 250px;
      }
      .highlight {
        float: left;
        width: calc(100% - 250px);
      }
      .work-block {
        border-bottom-width: 0;
        clear: none;
      }
    }
  }

  @media (max-width: 1024px) {
    .content {
      padding: 0;
    }
    .content-wrap {
      border-radius: 0;
      box-shadow: none;
      display: block;
    }
    .work {
      border-right-width: 0;
      box-shadow: none;
      margin: 0;
      max-width: none !important;
      min-width: 0;
      width: 100%;
    }
    .work-mobile-header {
      display: inline-block;
    }
    .work-title {
      height: auto;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .work-content {
      border-radius: 0;
    }
  }
</style>
