<template>
  <div class="work-content">
    <div class="work-content-wrap work-content-style">
      <div class="work-modules">
        <!-- This module can be generated by rich editor -->
        <!-- place holder 1400 x 1 px -->
        <div class="module-spacer">
          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABXgAAAABCAYAAABkHsaZAAAAHElEQVR42u3BAQ0AAADCoPdPbQ43oAAAAAAAuDQV4QABsr+jcAAAAABJRU5ErkJggg==" />
        </div>
        <div class="work-module full" v-for="(src, key) in srcs" :key="key" >
          <image-text :link="src" />
          <div class="spacer border">
            <div class="divider" />
          </div>
        </div>
        <div class="spacer">
          <div class="divider" />
        </div>
        <div class="work-module full">
          <text-text class-name="main-text">
            <div class="align-center p1"><a href="https://www.behance.net/gallery/52052475/Banu-Defender-Star-Citizen" target="_blank">Banu Defender - Star Citizen</a></div>
            <div class="spacer tiny">
              <div class="divider" />
            </div>
            <div class="p3">关于作者: <a href="https://pxhere.com" target="_blank">Jan Urschel</a></div>
            <div class="spacer border">
              <div class="divider" />
            </div>
            <div class="p3">Jan Urschel is a freelance concept designer and illustrator working in the entertainment industry, designing for feature films and video games. Clients include: Paramount Pictures, Warner Bros, Lucasfilm, Marvel, EA, Sony, Ubisoft, LucasArts, Cloud Imperium Games, Psyop etc.</div>
            <div class="spacer border">
              <div class="divider" />
            </div>
            <div class="p3">本页显示的图片仅为学习所用，不会用于商业，如有侵权请联系 x@xiak.com</div>
          </text-text>
        </div>
        <div class="work-module full">
          <div class="spacer medium">
            <div class="divider" />
          </div>
          <text-text class-name="code-text">
            <editor />
          </text-text>
        </div>
        <div v-html="htmlStr"></div>
      </div>
      <div class="spacer">
        <div class="divider"></div>
      </div>
    </div>
  </div>
</template>

<script>
import ImageText from '@/components/content/text-image';
import TextText from '@/components/content/text-text';
import Editor from '@/components/editor/editor';
import md from './markdown';

export default {
  components: {
    ImageText,
    TextText,
    Editor,
  },
  data() {
    return {
      srcs: [
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-1.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-2.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-3.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-4.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-5.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-6.jpg',
      ],
      htmlStr: '',
      markedStr: `# Header 1
![I](https://c.pxhere.com/photos/19/04/christmas_tree_lights_balls_red_gold_holiday_tree_winter-598441.jpg!d)
\`\`\`
This is Script
\`\`\`
`,
    };
  },
  mounted() {
    this.htmlStr = md(this.markedStr);
    console.info(this.htmlStr);
  },
};
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
  .work-content {
    padding-top: 0;
    background-color: #FFFFFF;
    border-radius: 3px 0 0;
  }
  .work-content-wrap {
    .work-modules {
      border-radius: 0;
      overflow: hidden;
    }
  }

  .module-spacer {
    height: 0;
    img {
      width: 100%;
    }
  }

  .p1 {
    font-size: 20px;
  }
  .p2 {
    font-size: 19px;
  }
  .p3 {
    font-size: 18px;
  }
  .p4 {
    font-size: 16px;
  }
  .p5 {
    font-size: 15px;
  }

  .align-center {
    text-align: center;
  }
  .work-module {
    padding: 0 7.1%;
    .main-text a {
      color: #1769FF;
      text-align: left;
      text-decoration: none;
    }
    &.align-center {
      margin-center: 0 !important;
    }
    &.full {
      padding-left: 0;
      padding-right: 0;
    }
  }

  .module {
    padding-bottom: 0px;
  }

  .module-spacer {
    height: 0;
    img {
      width: 100%;
    }
  }

  .spacer {
    height: 40px;
    &.border {
      height: 1px;
    }
    &.tiny {
      height: 10px;
    }
    &.mini {
      height: 20px;
    }
    &.medium {
      height: 30px;
    }
    &.large {
      height: 60px;
    }
  }

  .divider {
    display: none;
  }
  @media (max-width: 603px) {
    .p1 {
      font-size: 18px;
    }
    .p2 {
      font-size: 17px;
    }
    .p3 {
      font-size: 16px;
    }
    .p4 {
      font-size: 15px;
    }
    .p5 {
      font-size: 14px;
    }
  }
  @media (max-width: 1080px) and (min-width: 1024px) {
    .p1 {
      font-size: 20px;
    }
    .p2 {
      font-size: 19px;
    }
    .p3 {
      font-size: 18px;
    }
    .p4 {
      font-size: 17px;
    }
    .p5 {
      font-size: 16px;
    }
  }

</style>
