<template>
  <div class="work-content">
    <div class="work-content-wrap work-content-style">
      <div class="work-modules">
        <!-- This module can be generated by rich editor -->
        <!-- place holder 1400 x 1 px -->
        <div class="module-spacer">
          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABXgAAAABCAYAAABkHsaZAAAAHElEQVR42u3BAQ0AAADCoPdPbQ43oAAAAAAAuDQV4QABsr+jcAAAAABJRU5ErkJggg==" />
        </div>
        <div class="spacer">
          <div class="divider"></div>
        </div>
        <!--<div class="work-module full" v-for="(token, k) in tokens" :key="k">
          <image-text v-if="token.type === 'image'" />
          <text-text class-name="code-text" v-else-if="token.type === 'code'">
            <editor :code="token.text" :lang="token.lang" />
          </text-text>
          <text-text class-name="main-text" v-else>
            {{ token.text }}
          </text-text>
        </div>-->
        <div class="work-module markdown" v-editor v-html="htmlStr" ></div>
      </div>
      <div class="spacer">
        <div class="divider"></div>
      </div>
    </div>
  </div>
</template>

<script>
import editor from '@/directive/editor/index.js';
import marked from 'marked';

export default {
  directives: {
    editor,
  },
  data() {
    return {
      srcs: [
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-1.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-2.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-3.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-4.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-5.jpg',
        'https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-6.jpg',
      ],
      htmlStr: '',
      tokens: [],
      markedStr:
`
# 集群组件版本和配置

## 组件版本

### 核心组件
- Kubernetes 1.11.2
- Etcd 3.3.8
- Docker 18.06.0-ce
- Flanneld 0.10.0

### 插件
- Coredns
- Dashboard
- Heapster (influxdb、grafana)
- Metrics-Server
- EFK (elasticsearch、fluentd、kibana)

### 镜像仓库
- Docker registry
- harbor

## 配置
### etcd
- etcd和kubernetes分离, 以便在apiserver挂掉以后还可以继续工作

### kube-apiserver
- 使用 keepalived 和 haproxy 实现高可用
- 关闭非安全端口 8080 和匿名访问
- 在安全端口 \`6443\` 接收 https 请求
- 严格的认证和授权策略 (x509、token、RBAC)
- 开启 bootstrap token 认证，支持 kubelet TLS bootstrapping
- 使用 https 访问 kubelet、etcd，加密通信

### kube-controller-manager
- 高可用
- 关闭非安全端口，在安全端口 10252 接收 https 请求
- 使用 kubeconfig 访问 apiserver 的安全端口
- 自动 approve kubelet 证书签名请求 (CSR)，证书过期后自动轮转
- 各 controller 使用自己的 ServiceAccount 访问 apiserver

### kube-scheduler
- 高可用
- 使用 kubeconfig 访问 apiserver 的安全端口

### kubelet
- 使用 kubeconfig 访问 apiserver 的安全端口
- 使用 TLS bootstrap 机制自动生成 client 和 server 证书，过期后自动轮转
- 使用JSON文件配置主要参数
- 关闭只读端口，在安全端口 10250 接收 https 请求，对请求进行认证和授权，拒绝匿名访问和非授权访问

### kube-proxy
- 使用 kubeconfig 访问 apiserver 的安全端口
- 使用YAML文件配置主要参数
- 使用 ipvs 代理模式

### DNS
- 使用功能、性能更好的 coredns

### Dashboard
- 支持登录认证

### Metric
- heapster、metrics-server，使用 https 访问 kubelet 安全端口

### 日志
- Elasticsearch、Fluend、Kibana

### 镜像库
- docker-registry、harbor

## Picture
![T](https://mir-oss-cdn-sh.xiak.com/works/1400/janurschelbanu-defender-starc-citizen-6.jpg)

## Code
\`\`\`
export default {
  loginByUsername: config => {
    const { username } = JSON.parse(config.body)
    return userMap[username]
  },
  getUserInfo: config => {
    const { token } = param2Obj(config.url)
    if (userMap[token]) {
      return userMap[token]
    } else {
      return false
    }
  },
  logout: () => 'success'
}

\`\`\`
`,
    };
  },
  mounted() {
    const renderer = new marked.Renderer();
    const option = {
      renderer,
      gfm: true,
      tables: true,
      breaks: true,
      pedantic: false,
      sanitize: false,
      smartLists: true,
      smartypants: false,
    };
    marked.setOptions(option);
    // const lexer = new marked.Lexer(option);
    // const tokens = lexer.lex(this.markedStr);
    // console.info(tokens);
    // const inlineLexer = new marked.InlineLexer(tokens.links, option);
    // console.info(tokens.links);
    // const data = inlineLexer.output('![test](https://xiak.com)');
    // console.info(data);
    this.htmlStr = marked.parse(this.markedStr);
  },
};
</script>

<style rel="stylesheet/scss" lang="scss">
  .work-content {
    padding-top: 0;
    background-color: #FFFFFF;
    border-radius: 3px 0 0;
  }
  .work-content-wrap {
    .work-modules {
      border-radius: 0;
      overflow: hidden;
    }
  }

  .module-spacer {
    height: 0;
    img {
      width: 100%;
    }
  }

  .p1 {
    font-size: 20px;
  }
  .p2 {
    font-size: 19px;
  }
  .p3 {
    font-size: 18px;
  }
  .p4 {
    font-size: 16px;
  }
  .p5 {
    font-size: 15px;
  }

  .align-center {
    text-align: center;
  }
  .work-module {
    padding: 0 5%;
    overflow: hidden;
    .main-text a {
      color: #1769FF;
      text-align: left;
      text-decoration: none;
    }
    &.align-center {
      margin-center: 0 !important;
    }
    &.full {
      padding-left: 0;
      padding-right: 0;
    }
  }

  .module {
    padding-bottom: 0px;
  }

  .module-spacer {
    height: 0;
    img {
      width: 100%;
    }
  }

  .spacer {
    height: 40px;
    &.border {
      height: 1px;
    }
    &.tiny {
      height: 10px;
    }
    &.mini {
      height: 20px;
    }
    &.medium {
      height: 30px;
    }
    &.large {
      height: 60px;
    }
  }

  .divider {
    display: none;
  }
  @media (max-width: 603px) {
    .p1 {
      font-size: 18px;
    }
    .p2 {
      font-size: 17px;
    }
    .p3 {
      font-size: 16px;
    }
    .p4 {
      font-size: 15px;
    }
    .p5 {
      font-size: 14px;
    }
  }
  @media (max-width: 1080px) and (min-width: 1024px) {
    .p1 {
      font-size: 20px;
    }
    .p2 {
      font-size: 19px;
    }
    .p3 {
      font-size: 18px;
    }
    .p4 {
      font-size: 17px;
    }
    .p5 {
      font-size: 16px;
    }
  }
  .markdown {
    font-size: 18px;
    font-weight: 400;
    line-height: 1.7;
    color: #262626;
    p {
      margin: 0 0 10px;
    }
    h1 {
      font-size: 30px;
      margin-bottom: 30px;
      text-align: center;
    }
    h2 {
      font-size: 18px;
    }
    h3 {
      font-size: 16px;
    }
    ol, ul {
      margin-top: 0;
      margin-bottom: 10px;
    }
    code {
      color: #00ff00;
      background-color: #2b2b2b;
      border-radius: 3px;
    }
    img {
      height: 100%;
      width: 100%;
      display: inline-block;
      max-width: 100%;
      vertical-align: middle;
    }
  }
</style>
